baseurl: ""
url: "https://atinjin.github.io"
repository: "atinjin/atinjin.github.io"

markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  authors:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

sass:
  sass_dir: _sass
  style: compressed
